import type { Metadata } from "next";
import Navbar from "@/modules/Navbar/Navbar";
import Footer from "@/modules/Footer/Footer";
import "../styles/globals.scss";
import ThemeProvider from "@/theme/ThemeProvider";
import navbarContent from "@/content/navbar.json";
import footerContent from "@/content/footer.json";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider>
          <header>
            <Navbar
              brand={navbarContent.brand}
              menu={navbarContent.menu}
              themeToggleLabel={navbarContent.themeToggleLabel}
            />
          </header>
          <main id="page-content">
            <div className="container">{children}</div>
          </main>
          <footer>
            <Footer
              leftContent={footerContent.leftContent}
              social={footerContent.social}
              achievementText={footerContent.achievementText}
            />
          </footer>
        </ThemeProvider>
      </body>
    </html>
  );
}
